/*
 * CommonGui.h
 *
 *  Created on: 2014年1月26日
 *      Author: mabin
 */

#ifndef COMMONGUI_H_
#define COMMONGUI_H_

#include "cocos2d.h"
#include "cocos-ext.h"
#include "XMLParser.h"

//all events
//errors
#define YGO_EVENT_TYPE_CONNECTION_TIMEOUT "ygo_ev_type_connection_timeout"
#define YGO_EVENT_TYPE_CONNECTION_INTERRUPTED "ygo_ev_type_connection_interrupted"
#define YGO_EVENT_TYPE_JOIN_ERROR "ygo_ev_type_join_error"
#define YGO_EVENT_TYPE_DECK_ERROR "ygo_ev_type_deck_error"
#define YGO_EVENT_TYPE_SIDE_ERROR "ygo_ev_type_side_error"
#define YGO_EVENT_TYPE_VERSION_ERROR "ygo_ev_type_version_error"
//ops
#define YGO_EVENT_TYPE_SELECT_HAND "ygo_ev_type_select_hand"
#define YGO_EVENT_TYPE_SELECT_TP "ygo_ev_type_select_tp"
#define YGO_EVENT_TYPE_HAND_RESULT "ygo_ev_type_hand_result"
#define YGO_EVENT_TYPE_CHANGE_SIDE "ygo_ev_type_change_side"
#define YGO_EVENT_TYPE_WAITING_SIDE "ygo_ev_type_waiting_side"
#define YGO_EVENT_TYPE_TYPE_CHANGE "ygo_ev_type_type_change"
#define YGO_EVENT_TYPE_DUEL_START "ygo_ev_type_duel_start"
#define YGO_EVENT_TYPE_DUEL_END "ygo_ev_type_duel_end"
#define YGO_EVENT_TYPE_REPLAY "ygo_ev_type_replay"
#define YGO_EVENT_TYPE_TIME_LIMIT "ygo_ev_type_time_limit"
#define YGO_EVENT_TYPE_CHAT "ygo_ev_type_chat"
#define YGO_EVENT_TYPE_HOST_PLAYER_ENTER "ygo_ev_type_host_player_enter"
#define YGO_EVENT_TYPE_HOST_PLAYER_CHANGE "ygo_ev_type_host_player_change"
#define YGO_EVENT_TYPE_HOST_WATCH_CHANGE "ygo_ev_type_host_watch_change"
//msg during duel
#define YGO_EVENT_TYPE_MSG_RETRY "ygo_ev_type_msg_retry"
#define YGO_EVENT_TYPE_MSG_HINT "ygo_ev_type_msg_hint"
#define YGO_EVENT_TYPE_MSG_WIN "ygo_ev_type_msg_win"
#define YGO_EVENT_TYPE_MSG_WAITING "ygo_ev_type_msg_waiting"
#define YGO_EVENT_TYPE_MSG_START "ygo_ev_type_msg_start"
#define YGO_EVENT_TYPE_MSG_UPDATE_DATA "ygo_ev_type_msg_update_data"
#define YGO_EVENT_TYPE_MSG_UPDATE_CARD "ygo_ev_type_msg_update_card"
#define YGO_EVENT_TYPE_MSG_SELECT_BATTLE_CMD "ygo_ev_type_msg_select_battle_cmd"
#define YGO_EVENT_TYPE_MSG_SELECT_IDLE_CMD "ygo_ev_type_msg_select_idle_cmd"
#define YGO_EVENT_TYPE_MSG_SELECT_EFFECTYN "ygo_ev_type_msg_select_effect_yn"
#define YGO_EVENT_TYPE_MSG_SELECT_YESNO "ygo_ev_type_msg_select_yes_no"
#define YGO_EVENT_TYPE_MSG_SELECT_OPTION "ygo_ev_type_msg_select_option"
#define YGO_EVENT_TYPE_MSG_SELECT_CARD "ygo_ev_type_msg_select_card"
#define YGO_EVENT_TYPE_MSG_SELECT_CHAIN "ygo_ev_type_msg_select_chain"
#define YGO_EVENT_TYPE_MSG_SELECT_PLACE "ygo_ev_type_msg_select_place"
#define YGO_EVENT_TYPE_MSG_SELECT_DISFIELD "ygo_ev_type_msg_select_disfield"
#define YGO_EVENT_TYPE_MSG_SELECT_POSITION "ygo_ev_type_msg_select_position"
#define YGO_EVENT_TYPE_MSG_SELECT_TRIBUTE "ygo_ev_type_msg_select_tribute"
#define YGO_EVENT_TYPE_MSG_SELECT_COUNTER "ygo_ev_type_msg_select_counter"
#define YGO_EVENT_TYPE_MSG_SELECT_SUM "ygo_ev_type_msg_select_sum"
#define YGO_EVENT_TYPE_MSG_SORT_CARD "ygo_ev_type_msg_sort_card"
#define YGO_EVENT_TYPE_MSG_SORT_CHAIN "ygo_ev_type_msg_sort_chain"
#define YGO_EVENT_TYPE_MSG_CONFIRM_DESKTOP "ygo_ev_type_msg_confirm_desktop"
#define YGO_EVENT_TYPE_MSG_CONFIRM_CARDS "ygo_ev_type_msg_confirm_cards"
#define YGO_EVENT_TYPE_MSG_SHUFFLE_DECK "ygo_ev_type_msg_shuffle_deck"
#define YGO_EVENT_TYPE_MSG_SHUFFLE_HAND "ygo_ev_type_msg_shuffle_hand"
#define YGO_EVENT_TYPE_MSG_REFRESH_DECK "ygo_ev_type_msg_refresh_deck"
#define YGO_EVENT_TYPE_MSG_SWAP_GRAVE_DECK "ygo_ev_type_msg_swap_grave_deck"
#define YGO_EVENT_TYPE_MSG_REVERSE_DECK "ygo_ev_type_msg_reverse_deck"
#define YGO_EVENT_TYPE_MSG_DECK_TOP "ygo_ev_type_msg_deck_top"
#define YGO_EVENT_TYPE_MSG_SHUFFLE_SET_CARD "ygo_ev_type_msg_shuffle_set_card"
#define YGO_EVENT_TYPE_MSG_NEW_TURN "ygo_ev_type_msg_new_turn"
#define YGO_EVENT_TYPE_MSG_NEW_PHASE "ygo_ev_type_msg_new_phase"
#define YGO_EVENT_TYPE_MSG_MOVE "ygo_ev_type_msg_move"
#define YGO_EVENT_TYPE_MSG_POS_CHANGE "ygo_ev_type_msg_pos_change"
#define YGO_EVENT_TYPE_MSG_SET "ygo_ev_type_msg_set"
#define YGO_EVENT_TYPE_MSG_SWAP "ygo_ev_type_msg_swap"
#define YGO_EVENT_TYPE_MSG_FIELD_DISABLED "ygo_ev_type_msg_field_disabled"
#define YGO_EVENT_TYPE_MSG_SUMMONING "ygo_ev_type_msg_summoning"
#define YGO_EVENT_TYPE_MSG_SUMMONED "ygo_ev_type_msg_summoned"
#define YGO_EVENT_TYPE_MSG_SPSUMMONING "ygo_ev_type_msg_spsummoning"
#define YGO_EVENT_TYPE_MSG_SPSUMMONED "ygo_ev_type_msg_spsummoned"
#define YGO_EVENT_TYPE_MSG_FLIPSUMMONING "ygo_ev_type_msg_flipsummoning"
#define YGO_EVENT_TYPE_MSG_FLIPSUMMONED "ygo_ev_type_msg_flipsummoned"
#define YGO_EVENT_TYPE_MSG_CHAINING "ygo_ev_type_msg_chaining"
#define YGO_EVENT_TYPE_MSG_CHAINED "ygo_ev_type_msg_chained"
#define YGO_EVENT_TYPE_MSG_CHAIN_SOLVING "ygo_ev_type_msg_chain_solving"
#define YGO_EVENT_TYPE_MSG_CHAIN_SOLVED "ygo_ev_type_msg_chain_solving"
#define YGO_EVENT_TYPE_MSG_CHAIN_END "ygo_ev_type_msg_chain_end"
#define YGO_EVENT_TYPE_MSG_CHAIN_DISABLED "ygo_ev_type_msg_chain_disabled"
#define YGO_EVENT_TYPE_MSG_CHAIN_NEGATED "ygo_ev_type_msg_chain_negated"
#define YGO_EVENT_TYPE_MSG_CARD_SELECTED "ygo_ev_type_msg_card_selected"
#define YGO_EVENT_TYPE_MSG_RANDOM_SELECTED "ygo_ev_type_msg_random_selected"
#define YGO_EVENT_TYPE_MSG_BECOME_TARGET "ygo_ev_type_msg_become_target"
#define YGO_EVENT_TYPE_MSG_DRAW "ygo_ev_type_msg_draw"
#define YGO_EVENT_TYPE_MSG_DAMAGE "ygo_ev_type_msg_damage"
#define YGO_EVENT_TYPE_MSG_RECOVER "ygo_ev_type_msg_recover"
#define YGO_EVENT_TYPE_MSG_EQUIP "ygo_ev_type_msg_equip"
#define YGO_EVENT_TYPE_MSG_LPUPDATE "ygo_ev_type_msg_lpupdate"
#define YGO_EVENT_TYPE_MSG_UNEQUIP "ygo_ev_type_msg_unequip"
#define YGO_EVENT_TYPE_MSG_TARGET "ygo_ev_type_msg_target"
#define YGO_EVENT_TYPE_MSG_CANCEL_TARGET "ygo_ev_type_msg_cancel_target"
#define YGO_EVENT_TYPE_MSG_PAY_LPCOST "ygo_ev_type_msg_pay_lp_cost"
#define YGO_EVENT_TYPE_MSG_ADD_COUNTER "ygo_ev_type_msg_add_counter"
#define YGO_EVENT_TYPE_MSG_REMOVE_COUNTER "ygo_ev_type_msg_remove_counter"
#define YGO_EVENT_TYPE_MSG_ATTACK "ygo_ev_type_msg_attack"
#define YGO_EVENT_TYPE_MSG_BATTLE "ygo_ev_type_msg_battle"
#define YGO_EVENT_TYPE_MSG_ATTACK_DISABLED "ygo_ev_type_msg_attack_disabled"
#define YGO_EVENT_TYPE_MSG_DAMAGE_STEP_START "ygo_ev_type_msg_damage_step_start"
#define YGO_EVENT_TYPE_MSG_DAMAGE_STEP_END "ygo_ev_type_msg_damage_step_end"
#define YGO_EVENT_TYPE_MSG_MISSED_EFFECT "ygo_ev_type_msg_missed_effect"
#define YGO_EVENT_TYPE_MSG_TOSS_COIN "ygo_ev_type_msg_toss_coin"
#define YGO_EVENT_TYPE_MSG_TOSS_DICE "ygo_ev_type_msg_toss_dice"
#define YGO_EVENT_TYPE_MSG_ANNOUNCE_RACE "ygo_ev_type_msg_announce_race"
#define YGO_EVENT_TYPE_MSG_ANNOUNCE_ATTRIB "ygo_ev_type_msg_announce_attrib"
#define YGO_EVENT_TYPE_MSG_ANNOUNCE_CARD "ygo_ev_type_msg_announce_card"
#define YGO_EVENT_TYPE_MSG_ANNOUNCE_NUMBER "ygo_ev_type_msg_announce_number"
#define YGO_EVENT_TYPE_MSG_CARD_HINT "ygo_ev_type_msg_card_hint"
#define YGO_EVENT_TYPE_MSG_MATCH_KILL "ygo_ev_type_msg_match_kill"
#define YGO_EVENT_TYPE_MSG_TAG_SWAP "ygo_ev_type_msg_tag_swap"
#define YGO_EVENT_TYPE_MSG_RELOAD_FIELD "ygo_ev_type_msg_reload_field"


#define CARD_THUMBNAIL_HEIGHT (64)
#define CARD_THUMBNAIL_WIDTH (44)
#define CARD_DECK_MIN_COUNT 40
#define CARD_DECK_MAX_COUNT 60
#define CARD_FEILD_ORIG_HEIGHT 37

//menu layer
#define MAIN_MENU_LAYER 100000

//Lan Mode
#define LAN_MODE_TAG_BASE 0
#define LAN_MODE_TEXT_LABEL_NICK_NAME (LAN_MODE_TAG_BASE + 0)
#define LAN_MODE_TEXT_FIELD_NICK_NAME (LAN_MODE_TAG_BASE + 1)
#define LAN_MODE_BUTTON_CREATE_HOST (LAN_MODE_TAG_BASE + 2)
#define LAN_MODE_LIST_VIEW_HOSTS (LAN_MODE_TAG_BASE + 3)
#define LAN_MODE_BUTTON_REFRESH (LAN_MODE_TAG_BASE + 4)
#define LAN_MODE_TEXT_LABEL_ADDRESS (LAN_MODE_TAG_BASE + 5)
#define LAN_MODE_TEXT_FIELD_ADDRESS (LAN_MODE_TAG_BASE + 6)
#define LAN_MODE_TEXT_FIELD_PORT (LAN_MODE_TAG_BASE + 7)
#define LAN_MODE_BUTTON_JOIN_GAME (LAN_MODE_TAG_BASE + 8)
#define LAN_MODE_TEXT_LABEL_PASSWORD (LAN_MODE_TAG_BASE + 9)
#define LAN_MODE_TEXT_FIELD_PASSWORD (LAN_MODE_TAG_BASE + 10)
#define LAN_MODE_BUTTON_CANCEL (LAN_MODE_TAG_BASE + 11)
//Lan Mode-create server
#define CREATE_SERVER_LABEL_LIMIT_LIST (LAN_MODE_TAG_BASE + 12)
#define CREATE_SERVER_LIST_LIMIT_LIST (LAN_MODE_TAG_BASE + 13)
#define CREATE_SERVER_LABEL_CARD_ALLOWED (LAN_MODE_TAG_BASE + 14)
#define CREATE_SERVER_LIST_CARD_ALLOWED (LAN_MODE_TAG_BASE + 15)
#define CREATE_SERVER_LABEL_DUEL_MODE (LAN_MODE_TAG_BASE + 16)
#define CREATE_SERVER_LIST_DUEL_MODE (LAN_MODE_TAG_BASE + 17)
#define CREATE_SERVER_LABEL_LIMIT_EACH_ROUND (LAN_MODE_TAG_BASE + 18)
#define CREATE_SERVER_TEXT_FIELD_LIMIT_EACH_ROUND (LAN_MODE_TAG_BASE + 19)
#define CREATE_SERVER_LABEL_EXTRA_SETTINGS (LAN_MODE_TAG_BASE + 20)
#define CREATE_SERVER_CHECKBOX_ALLOW_CARD_EFFECTS_PRIVILEGE (LAN_MODE_TAG_BASE + 21)
#define CREATE_SERVER_LABEL_ALLOW_CARD_EFFECTS_PRIVILEGE (LAN_MODE_TAG_BASE + 22)
#define CREATE_SERVER_LABEL_INITIAL_LIFE_POINTS (LAN_MODE_TAG_BASE + 23)
#define CREATE_SERVER_TEXT_FIELD_INITIAL_LIFE_POINTS (LAN_MODE_TAG_BASE + 24)
#define CREATE_SERVER_CHECKBOX_IGNORE_DECK_CHECK (LAN_MODE_TAG_BASE + 25)
#define CREATE_SERVER_LABEL_IGNORE_DECK_CHECK (LAN_MODE_TAG_BASE + 26)
#define CREATE_SERVER_LABEL_INITIAL_CARD_IN_HAND (LAN_MODE_TAG_BASE + 27)
#define CREATE_SERVER_TEXT_FIELD_INITIAL_CARD_IN_HAND (LAN_MODE_TAG_BASE + 28)
#define CREATE_SERVER_CHECKBOX_IGNORE_DECK_SHUFFLE (LAN_MODE_TAG_BASE + 29)
#define CREATE_SERVER_LABEL_IGNORE_DECK_SHUFFLE  (LAN_MODE_TAG_BASE + 30)
#define CREATE_SERVER_LABEL_DRAW_EACH_ROUND (LAN_MODE_TAG_BASE + 31)
#define CREATE_SERVER_TEXT_FIELD_DRAW_EACH_ROUND (LAN_MODE_TAG_BASE + 32)
#define CREATE_SERVER_LABEL_HOST_NAME (LAN_MODE_TAG_BASE + 33)
#define CREATE_SERVER_TEXT_FIELD_HOST_NAME  (LAN_MODE_TAG_BASE + 34)
#define CREATE_SERVER_LABEL_PASSWORD (LAN_MODE_TAG_BASE + 35)
#define CREATE_SERVER_TEXT_FIELD_PASSWORD (LAN_MODE_TAG_BASE + 36)
#define CREATE_SERVER_BUTTON_CONFIRM (LAN_MODE_TAG_BASE + 37)
#define CREATE_SERVER_BUTTON_CANCEL (LAN_MODE_TAG_BASE + 38)
//Lan Mode-duel prepare
#define DUEL_PREPARE_BUTTON_DUELIST (LAN_MODE_TAG_BASE + 39)
#define DUEL_PREPARE_PANEL_DUEL_INFO (LAN_MODE_TAG_BASE + 40)
#define DUEL_PREPARE_BUTTON_KICK_1 (LAN_MODE_TAG_BASE + 41)
#define DUEL_PREPARE_LABEL_NICK_NAME_1 (LAN_MODE_TAG_BASE + 42)
#define DUEL_PREPARE_CHECKBOX_1 (LAN_MODE_TAG_BASE + 43)
#define DUEL_PREPARE_BUTTON_KICK_2 (LAN_MODE_TAG_BASE + 44)
#define DUEL_PREPARE_LABEL_NICK_NAME_2 (LAN_MODE_TAG_BASE + 45)
#define DUEL_PREPARE_CHECKBOX_2 (LAN_MODE_TAG_BASE + 46)
#define DUEL_PREPARE_BUTTON_WATCH_DUEL (LAN_MODE_TAG_BASE + 47)
#define DUEL_PREPARE_LABEL_DECK_LIST (LAN_MODE_TAG_BASE + 48)
#define DUEL_PREPARE_LIST_DECK_LIST (LAN_MODE_TAG_BASE + 49)
#define DUEL_PREPARE_BUTTON_START (LAN_MODE_TAG_BASE + 50)
#define DUEL_PREPARE_BUTTON_CANCEL (LAN_MODE_TAG_BASE + 51)
#define DUEL_PREPARE_TEXTFIELD_CHAT (LAN_MODE_TAG_BASE + 52)
#define DUEL_PREPARE_LABEL_INFO_LIMIT_LIST (LAN_MODE_TAG_BASE + 53)
#define DUEL_PREPARE_LABEL_INFO_CARD_ALLOWED (LAN_MODE_TAG_BASE + 54)
#define DUEL_PREPARE_LABEL_INFO_DUEL_MODE (LAN_MODE_TAG_BASE + 55)
#define DUEL_PREPARE_LABEL_INFO_LIMIT_EACH_ROUND (LAN_MODE_TAG_BASE + 56)
#define DUEL_PREPARE_LABEL_INFO_INITIAL_LIFE_POINTS (LAN_MODE_TAG_BASE + 58)
#define DUEL_PREPARE_LABEL_INFO_INITIAL_CARD_IN_HAND (LAN_MODE_TAG_BASE + 59)
#define DUEL_PREPARE_LABEL_INFO_DRAW_EACH_ROUND (LAN_MODE_TAG_BASE + 60)


#define LAN_MODE_MAIN_WIDGET_TAG (LAN_MODE_TAG_BASE + 10000)
#define CREATE_SERVER_MAIN_WIDGET (LAN_MODE_TAG_BASE + 10002)
#define LAN_MODE_LAYER (LAN_MODE_TAG_BASE + 10001)

//Deck Edit
#define DECK_EDIT_TAG_BASE 100
#define DECK_EDIT_PANEL_MAIN_DECK (DECK_EDIT_TAG_BASE + 0)
#define DECK_EDIT_PANEL_EXTRA_DECK (DECK_EDIT_TAG_BASE + 1)
#define DECK_EDIT_PANEL_SIDE_DECK (DECK_EDIT_TAG_BASE + 2)
#define DECK_EDIT_PANEL_CARD_DETAIL (DECK_EDIT_TAG_BASE + 3)
#define DECK_EDIT_LABEL_LIMIT_LIST (DECK_EDIT_TAG_BASE + 4)
#define DECK_EDIT_PANEL_LIMIT_DETAIL (DECK_EDIT_TAG_BASE + 5)
#define DECK_EDIT_LABEL_DECK_LIST (DECK_EDIT_TAG_BASE + 6)
#define DECK_EDIT_PANEL_DECK_DETAIL (DECK_EDIT_TAG_BASE + 7)
#define DECK_EDIT_BUTTON_SAVE (DECK_EDIT_TAG_BASE + 8)
#define DECK_EDIT_TEXT_FIELD_SAVE_AS (DECK_EDIT_TAG_BASE + 9)
#define DECK_EDIT_BUTTON_SAVE_AS (DECK_EDIT_TAG_BASE + 10)
#define DECK_EDIT_BUTTON_QUIT (DECK_EDIT_TAG_BASE + 11)
#define DECK_EDIT_BUTTON_SHUFFLE_DECK (DECK_EDIT_TAG_BASE + 12)
#define DECK_EDIT_BUTTON_SORT_DECK (DECK_EDIT_TAG_BASE + 13)
#define DECK_EDIT_BUTTON_CLEAN_DECK (DECK_EDIT_TAG_BASE + 14)
#define DECK_EDIT_PANEL_FILTER_CARD_CATEGORY (DECK_EDIT_TAG_BASE + 15)
#define DECK_EDIT_PANEL_FILTER_CARD_CATEGORY_DETAIL (DECK_EDIT_TAG_BASE + 16)
#define DECK_EDIT_PANEL_FILTER_CARD_LIMIT (DECK_EDIT_TAG_BASE + 17)
#define DECK_EDIT_PANEL_FILTER_PROPERTY (DECK_EDIT_TAG_BASE + 18)
#define DECK_EDIT_PANEL_FILTER_ATK (DECK_EDIT_TAG_BASE + 19)
#define DECK_EDIT_PANEL_FILTER_DEF (DECK_EDIT_TAG_BASE + 20)
#define DECK_EDIT_PANEL_FILTER_RACE (DECK_EDIT_TAG_BASE + 21)
#define DECK_EDIT_PANEL_FILTER_KEYWORD (DECK_EDIT_TAG_BASE + 22)
#define DECK_EDIT_PANEL_FILTER_STAR (DECK_EDIT_TAG_BASE + 23)
#define DECK_EDIT_BUTTON_EFFECT (DECK_EDIT_TAG_BASE + 24)
#define DECK_EDIT_BUTTON_RESTART_SEARCH (DECK_EDIT_TAG_BASE + 25)
#define DECK_EDIT_LABEL_MAIN_DECK (DECK_EDIT_TAG_BASE + 26)
#define DECK_EDIT_LABEL_SEARCH_RESULT (DECK_EDIT_TAG_BASE + 27)
#define DECK_EDIT_PANEL_CARD_DESCRIPTION (DECK_EDIT_TAG_BASE + 28)
#define DECK_EDIT_LABEL_EXTRA_DECK (DECK_EDIT_TAG_BASE + 29)
#define DECK_EDIT_LIST_VIEW_SEARCH_RESULT (DECK_EDIT_TAG_BASE + 30)
#define DECK_EDIT_LABEL_SIDE_DECK (DECK_EDIT_TAG_BASE + 31)
#define DECK_EDIT_LABEL_FILTER_CARD_CATEGORY (DECK_EDIT_TAG_BASE + 32)
#define DECK_EDIT_LABEL_FILTER_CARD_PROPERTY (DECK_EDIT_TAG_BASE + 33)
#define DECK_EDIT_LABEL_FILTER_CARD_RACE (DECK_EDIT_TAG_BASE + 34)
#define DECK_EDIT_LABEL_FILTER_CARD_LIMIT (DECK_EDIT_TAG_BASE + 35)
#define DECK_EDIT_DECK_RELATE_PANEL (DECK_EDIT_TAG_BASE + 10000)
#define DECK_EDIT_CARD_RELATE_PANEL (DECK_EDIT_TAG_BASE + 10001)
#define DECK_EDIT_LAYER (LAN_MODE_TAG_BASE + 10002)

//Duel Field
#define DUEL_FIELD_TAG_BASE 200
#define DUEL_FIELD_PANEL_CARD_IN_HAND (DUEL_FIELD_TAG_BASE + 0)
#define DUEL_FIELD_IMAGE_CARD_DETAIL (DUEL_FIELD_TAG_BASE + 1)
#define DUEL_FIELD_PANEL_CARD_DETAIL (DUEL_FIELD_TAG_BASE + 2)
#define DUEL_FIELD_IMAGE_DUEL_FIELD (DUEL_FIELD_TAG_BASE + 3)
#define DUEL_FIELD_PANEL_LIFE_POINTS_1 (DUEL_FIELD_TAG_BASE + 4)
#define DUEL_FIELD_PANEL_LIFE_POINTS_2 (DUEL_FIELD_TAG_BASE + 5)
#define DUEL_FIELD_LABEL_LIFE_POINTS_1 (DUEL_FIELD_TAG_BASE + 6)
#define DUEL_FIELD_LABEL_LIFE_POINTS_2 (DUEL_FIELD_TAG_BASE + 7)
#define DUEL_FIELD_BAR_LIFE_POINTS_1 (DUEL_FIELD_TAG_BASE + 8)
#define DUEL_FIELD_BAR_LIFE_POINTS_2 (DUEL_FIELD_TAG_BASE + 9)
#define DUEL_FIELD_BUTTON_SURRENDER (DUEL_FIELD_TAG_BASE + 10)
#define DUEL_FIELD_PANEL_FIELD_1 (DUEL_FIELD_TAG_BASE + 11)
#define DUEL_FIELD_PANEL_EXTRA_1 (DUEL_FIELD_TAG_BASE + 12)
#define DUEL_FIELD_PANEL_MZONE1_1 (DUEL_FIELD_TAG_BASE + 13)
#define DUEL_FIELD_PANEL_MZONE2_1 (DUEL_FIELD_TAG_BASE + 14)
#define DUEL_FIELD_PANEL_MZONE3_1 (DUEL_FIELD_TAG_BASE + 15)
#define DUEL_FIELD_PANEL_MZONE4_1 (DUEL_FIELD_TAG_BASE + 16)
#define DUEL_FIELD_PANEL_MZONE5_1 (DUEL_FIELD_TAG_BASE + 17)
#define DUEL_FIELD_PANEL_SZONE1_1 (DUEL_FIELD_TAG_BASE + 18)
#define DUEL_FIELD_PANEL_SZONE2_1 (DUEL_FIELD_TAG_BASE + 19)
#define DUEL_FIELD_PANEL_SZONE3_1 (DUEL_FIELD_TAG_BASE + 20)
#define DUEL_FIELD_PANEL_SZONE4_1 (DUEL_FIELD_TAG_BASE + 21)
#define DUEL_FIELD_PANEL_SZONE5_1 (DUEL_FIELD_TAG_BASE + 22)
#define DUEL_FIELD_PANEL_REMOVE_1 (DUEL_FIELD_TAG_BASE + 23)
#define DUEL_FIELD_PANEL_GROVE_1 (DUEL_FIELD_TAG_BASE + 24)
#define DUEL_FIELD_PANEL_DECK_1 (DUEL_FIELD_TAG_BASE + 25)
#define DUEL_FIELD_PANEL_FIELD_2 (DUEL_FIELD_TAG_BASE + 26)
#define DUEL_FIELD_PANEL_EXTRA_2 (DUEL_FIELD_TAG_BASE + 27)
#define DUEL_FIELD_PANEL_MZONE1_2 (DUEL_FIELD_TAG_BASE + 28)
#define DUEL_FIELD_PANEL_MZONE2_2 (DUEL_FIELD_TAG_BASE + 29)
#define DUEL_FIELD_PANEL_MZONE3_2 (DUEL_FIELD_TAG_BASE + 30)
#define DUEL_FIELD_PANEL_MZONE4_2 (DUEL_FIELD_TAG_BASE + 31)
#define DUEL_FIELD_PANEL_MZONE5_2 (DUEL_FIELD_TAG_BASE + 32)
#define DUEL_FIELD_PANEL_SZONE1_2 (DUEL_FIELD_TAG_BASE + 33)
#define DUEL_FIELD_PANEL_SZONE2_2 (DUEL_FIELD_TAG_BASE + 34)
#define DUEL_FIELD_PANEL_SZONE3_2 (DUEL_FIELD_TAG_BASE + 35)
#define DUEL_FIELD_PANEL_SZONE4_2 (DUEL_FIELD_TAG_BASE + 36)
#define DUEL_FIELD_PANEL_SZONE5_2 (DUEL_FIELD_TAG_BASE + 37)
#define DUEL_FIELD_PANEL_REMOVE_2 (DUEL_FIELD_TAG_BASE + 38)
#define DUEL_FIELD_PANEL_GROVE_2 (DUEL_FIELD_TAG_BASE + 39)
#define DUEL_FIELD_PANEL_DECK_2 (DUEL_FIELD_TAG_BASE + 40)




#endif /* COMMONGUI_H_ */
